version: "3.9"
services:
  postgres:
   image: postgres:14
   container_name: postgres_mlflow
   environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
   volumes:
    - postgres_data:/var/lib/postgresql/data
   ports:
    - "5432:5432"
  mlflow:
    build: 
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_server
    depends_on:
      - postgres
    ports:
      - "5500:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_ARTIFACT_ROOT=/mlartifacts
    volumes:
      - ./mlartifacts:/mlartifacts
    command: >
      mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      --default-artifact-root /mlartifacts
      --host 0.0.0.0
      --port 5000

  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlartifacts:/mlartifacts
    
  train:
    build:
      context: .
    container_name: model_trainer
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: ["python", "train.py"]
    volumes:
      - ./mlartifacts:/mlartifacts

    
volumes:
  postgres_data:
  
